Repository kpi-ua/intellect.kpi.ua, pull requests merged in 2023-12, with the labels that each got.

#83 SSR
  .eslintrc.json
  .github/workflows/workflow.yml
  .gitignore
  Dockerfile
  debug.dockerfile
  next-env.d.ts
  next.config.js
  package-lock.json
  package.json
  postcss.config.js
  src/App.tsx
  src/components/Avatar/Avatar.tsx
  src/components/Burger/Burger.tsx
  src/components/Footer/Footer.tsx
  src/components/Header/Header.module.css
  src/components/Header/Header.tsx
  src/components/I-TeacherCard/I-TeacherCard.tsx
  src/components/I-TeacherSearch/I-TeacherSearch.module.css
  src/components/I-TeacherSearch/I-TeacherSearch.tsx
  src/components/InfoBlock/InfoBlock.tsx
  src/components/TabList/TabList.module.css
  src/components/TabList/TabList.tsx
  src/components/TagsBlock/TagsBlock.tsx
  src/components/pages/I-About/I-About.tsx
  src/index.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/about.tsx
  src/pages/contacts.tsx
  src/pages/index.tsx
  src/pages/layout.tsx
  src/pages/profile/[teacherId].tsx
  src/pages/search.tsx
  src/router/index.tsx
  src/styles/global.css
  tailwind.config.js
  tsconfig.json
Labels: enhancement

#94 Search pagination
  src/@types/index.d.ts
  src/api/teacher.ts
  src/constants.ts
  src/pages/search.tsx
  src/utils/index.ts
Labels: bug

#93 Papers list tab layout small fixes
  src/components/DataList/DataList.tsx
  src/pages/profile/[teacherId].tsx
Labels: bug, enhancement

#112 Fix some UI issues
  public/favicon.ico
  src/components/Footer/Footer.tsx
  src/pages/_app.tsx
  src/pages/contacts.tsx
  src/pages/profile/[teacherId].tsx
  src/styles/global.css
Labels: bug

#113 Profile links - improved links rendering
  src/components/I-ProfileDetails/I-ProfileDetails.tsx
  src/pages/_app.tsx
  src/pages/profile/[teacherId].tsx
  src/styles/global.css
Labels: enhancement
